version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: "--config=/etc/otel-collector-config.yaml ${OTELCOL_ARGS}"
    # Change the "source" path below to swap out collector config files!
    volumes:
      - type: bind
        source: /home/developer/src/otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55670:55679" # zpages extension
      - "55681:55681" # http
    depends_on:
      - jaeger
    networks:
      - otel-net
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
    networks:
      - otel-net
    environment:
      - QUERY_BASE_PATH=/jaeger

networks:
  otel-net:  
